version: '3.8'

services:
  met-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: met-app
    ports:
      - "3001:3001"
    volumes:
      - ./docker/data:/app/data
      - ./docker/data/database.sqlite:/app/database.sqlite
    restart: unless-stopped
