version: '3.8'

services:
  met-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: met-app
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
