version: '3.8'

services:
  met-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: met-app
    ports:
      - "3001:3001"
    volumes:
      - ./docker/data/inventory.json:/app/inventory.json
      - ./docker/data/logs.json:/app/logs.json
      - ./docker/data/employees.json:/app/employees.json
      - ./docker/data/verifications.json:/app/verifications.json
      - ./docker/data/prices.json:/app/prices.json
    restart: unless-stopped
